# Generated by Django 3.2.5 on 2021-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_form',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
