# Generated by Django 3.2.5 on 2021-08-26 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_boy', '0002_delivery_form_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('pincode', models.IntegerField()),
                ('licenses', models.CharField(max_length=10)),
                ('working_form', models.TimeField()),
                ('working_to', models.TimeField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('range_of_delivery', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vehicle', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='Delivery')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
