# Generated by Django 3.2.5 on 2021-08-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0003_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='licenses',
        ),
    ]
