# Generated by Django 3.2.5 on 2021-09-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0004_remove_delivery_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='aadhar_card_image',
            field=models.ImageField(default='', upload_to='Delivery/aadhar_card'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driving_licence_image',
            field=models.ImageField(default='', upload_to='Delivery/driving_licence'),
        ),
    ]
