# Generated by Django 3.2.5 on 2021-08-25 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('hotel_number', models.IntegerField()),
                ('hotel_email', models.CharField(max_length=50)),
                ('shop_license_number', models.IntegerField(blank=True, null=True)),
                ('fssai_number', models.IntegerField(blank=True, null=True)),
                ('fssai_image', models.FileField(blank=True, null=True, upload_to='fssai')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_image', models.ImageField(upload_to='hotel_image')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_register.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('pincode', models.IntegerField()),
                ('cuisine', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('serving_form', models.TimeField()),
                ('serving_till', models.TimeField()),
                ('delivery', models.CharField(max_length=10)),
                ('loc', models.CharField(max_length=100)),
                ('open_status', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='Restaurant')),
                ('img2', models.ImageField(upload_to='Locality')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='registation_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_register.hotel_form'),
        ),
    ]
