# Generated by Django 3.2.5 on 2021-08-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='menu')),
                ('food_type', models.CharField(choices=[('Vegetarian', 'vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Dessert', 'Dessert')], max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_register.hotel')),
            ],
        ),
    ]
