# Generated by Django 3.2.5 on 2021-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_register', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default=2, upload_to='hotel_image'),
            preserve_default=False,
        ),
    ]
