# Generated by Django 3.2.5 on 2021-12-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_register', '0005_alter_menu_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
