# Generated by Django 3.2.5 on 2021-12-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_register', '0007_menu_sugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='menu',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
