# Generated by Django 3.2.5 on 2021-09-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='hotel',
        ),
    ]
