# Generated by Django 3.2.5 on 2021-09-11 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_register', '0005_alter_menu_food_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_rename_product_rating_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_register.hotel')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_register.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
