# Generated by Django 3.2.5 on 2021-09-13 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0005_auto_20210908_1258'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('delivery_time', models.DateField()),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_boy.delivery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
