# Generated by Django 3.2.6 on 2021-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='food.Cart'),
        ),
    ]
