# Generated by Django 3.2.5 on 2021-09-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_register', '0005_alter_menu_food_type'),
        ('food', '0013_auto_20210921_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(to='hotel_register.Menu'),
        ),
    ]
