# Generated by Django 3.2.5 on 2021-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20210921_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(to='food.Cart'),
        ),
    ]
