# Generated by Django 3.2.5 on 2021-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_register', '0005_alter_menu_food_type'),
        ('food', '0015_alter_order_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(to='hotel_register.Menu'),
        ),
    ]
