# Generated by Django 3.2.5 on 2021-09-22 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='delivery_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='application_form',
            name='delivery_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
