# Generated by Django 3.2.5 on 2021-09-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_auto_20210922_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
