# Generated by Django 3.2.5 on 2021-10-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='hotels_address',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
