# Generated by Django 3.2.5 on 2021-10-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_application_form_hotels_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_form',
            name='hotels_address',
        ),
        migrations.AddField(
            model_name='application_form',
            name='delivery_address',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='application_form',
            name='pickup_address',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
